export enum Events {
  TRANSITION_SCHEDULED = "START_SCHEDULED",
  TRANSITION_DONE = "START",
  TRANSITION_ABORT = "START_ABORT",
  STOP_SCHEDULED = "START_SCHEDULED",
  STOP = "STOP",
  STOP_ABORT = "STOP_ABORT",
}
