export enum Events {
  TRANSITION_SCHEDULED = "TRANSITION_SCHEDULED",
  TRANSITION_DONE = "TRANSITION_DONE",
  TRANSITION_ABORT = "TRANSITION_ABORT",
  STOP_SCHEDULED = "STOP_SCHEDULED",
  STOP = "STOP",
  STOP_ABORT = "STOP_ABORT",
}
